# Integers (whole numbers)
age = 25
print(age)

# Floats (decimal numbers)
price = 19.99
print(price)

# Strings (Text)
name = "Alice"
print(name)

#Booleans (True or False)
is_active = True
print(is_active)

# Lists (Ordered, changable collections)
fruits = ["apple", "banana", "cherry"]
print(fruits)

# Dictionaries (Key-value pairs)
person = {"name": "Bob", "age": 30}
print(person)

# Multiple assignments on one line
x, y, z = "Orange", "Banana", "Cherry"
print(x)
print(y)
print(z)

# Same value to multiple variables
a = b = c = "Python"
print(a)
print(b)
print(c)

#Swapping variables (unique to python)
a, b = "Red", "Blue"
a, b = b, a # Now a is 'blue' and b is 'red'
print(a)
print(b)