# Printing a greeting message
print("Hello World!")

# Printing my name
print("My name is Kovid Bhatt")

# Printing a fun fact about myself
# print("A fun fact about me is that I love to play basketball and I have been playing it since I was 9 years old.")
print("A fun fact about me is that I love to play basketball and I have been playing it since I was 9 years old.")

# Performing and printing a simple calculation
print("The result of 5 + 3 is:", 5 + 3)

# Printing my daily routine
print("My daily routine includes going to the park and jogging for 30 minutes, then I have breakfast and I go to school. After school, I would take some rest and then I would do my homework. After doing so, I go to the park and play with them for 1 hour 30 minutes. After that, I have dinner and then I go to sleep.")

# Performing and printing a complex calculation
print("The result of 5 ^ 3 is:", 5 ** 3)
# Performing and printing a simple calculation
print("The result of 10 - 4 is:", 10 - 4)
# Performing and printing a simple calculation
print("The result of 6 * 7 is:", 6 * 7)
# Performing and printing a simple calculation
print("The result of 20 / 6 is:", 20 / 6)